asset_path: /home/hassaan/robotics/isaac_tuts/02_Sim2Real/marker_pick_place/assets/banana/banana.obj
usd_dir: /home/hassaan/robotics/isaac_tuts/02_Sim2Real/marker_pick_place/assets/banana/usd
usd_file_name: banana_convex_decomposition.usd
force_usd_conversion: false
make_instanceable: true
mass_props:
  mass: 0.12
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: false
  linear_damping: 0.03
  angular_damping: 0.03
  max_linear_velocity: 1.0
  max_angular_velocity: 180.0
  max_depenetration_velocity: 1.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: 16
  solver_velocity_iteration_count: 4
  sleep_threshold: 0.001
  stabilization_threshold: 0.0001
collision_props:
  collision_enabled: true
  contact_offset: 0.002
  rest_offset: 0.0
  torsional_patch_radius: null
  min_torsional_patch_radius: null
mesh_collision_props:
  usd_func: pxr.UsdPhysics:MeshCollisionAPI
  physx_func: pxr.PhysxSchema:PhysxConvexDecompositionCollisionAPI
  mesh_approximation_name: convexDecomposition
  hull_vertex_limit: null
  max_convex_hulls: 16
  min_thickness: null
  voxel_resolution: 100000
  error_percentage: 5.0
  shrink_wrap: null
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2026-04-29 at 17:25:12.
##
